import axios from "axios";
import { getToken } from "./token";

const client = axios.create({
  baseURL: `${process.env.REACT_APP_BACKEND_URL}/api`,
  withCredentials: true,
});

client.interceptors.request.use((cfg) => {
  const t = getToken();
  if (t) cfg.headers.Authorization = `Bearer ${t}`;
  return cfg;
});

export const api = {
  login: (email, password, remember = true) =>
    client.post("/auth/login", { email, password, remember }).then((r) => r.data),
  logout: () => client.post("/auth/logout").then((r) => r.data),
  me: () => client.get("/auth/me").then((r) => r.data),
  googleSession: (session_id) => client.post("/auth/session", { session_id }).then((r) => r.data),
  forgotPassword: (email) => client.post("/auth/forgot-password", { email }).then((r) => r.data),
  resetPassword: (token, password) =>
    client.post("/auth/reset-password", { token, password }).then((r) => r.data),

  listEmployees: (params) => client.get("/employees", { params: params || {} }).then((r) => r.data),
  createEmployee: (d) => client.post("/employees", d).then((r) => r.data),
  updateEmployee: (id, d) => client.put(`/employees/${id}`, d).then((r) => r.data),
  deleteEmployee: (id) => client.delete(`/employees/${id}`).then((r) => r.data),
  importEmployees: (file) => { const fd = new FormData(); fd.append("file", file); return client.post("/employees/import", fd).then((r) => r.data); },
  importDepartments: (file) => { const fd = new FormData(); fd.append("file", file); return client.post("/departments/import", fd).then((r) => r.data); },
  downloadTemplate: (kind) => client.get(`/${kind}/template`, { responseType: "blob" }).then((r) => r.data),

  budgetPreview: (id, override, params) => client.post(`/employees/${id}/budget-preview`, { override }, { params }).then((r) => r.data),
  saveBudgetOverride: (id, override, params) => client.put(`/employees/${id}/budget-override`, { override }, { params }).then((r) => r.data),
  applyAugmentation: (body, params) => client.post("/budget/apply-augmentation", body, { params }).then((r) => r.data),

  getHypotheses: (year) => client.get("/hypotheses", { params: year ? { year } : {} }).then((r) => r.data),
  updateHypotheses: (d, year) => client.put("/hypotheses", d, { params: year ? { year } : {} }).then((r) => r.data),
  getBudget: (params) => client.get("/budget", { params }).then((r) => r.data),
  getBudgetCompare: (params) => client.get("/budget/compare", { params }).then((r) => r.data),
  getBudgetEvolution: (params) => client.get("/budget/evolution", { params }).then((r) => r.data),

  listYears: () => client.get("/years").then((r) => r.data),
  createYear: (d) => client.post("/years", d).then((r) => r.data),
  setActiveYear: (year) => client.put("/years/active", { year }).then((r) => r.data),

  downloadEmployeeFiche: (eid, year, scenario) => client.get(`/employees/${eid}/fiche-pdf`, { params: { ...(year ? { year } : {}), ...(scenario ? { scenario } : {}) }, responseType: "blob" }).then((r) => r.data),

  getLocks: (params) => client.get("/budget/locks", { params }).then((r) => r.data),
  setLock: (d) => client.post("/budget/lock", d).then((r) => r.data),
  getBudgetNoEntry: (params) => client.get("/budget/no-entry", { params }).then((r) => r.data),
  inactivateNoEntry: (params) => client.post("/budget/inactivate-no-entry", {}, { params }).then((r) => r.data),

  listUsers: () => client.get("/users").then((r) => r.data),
  createUser: (d) => client.post("/users", d).then((r) => r.data),
  updateUser: (id, d) => client.put(`/users/${id}`, d).then((r) => r.data),
  deactivateUser: (id) => client.delete(`/users/${id}`).then((r) => r.data),
  deleteUser: (id) => client.delete(`/users/${id}`).then((r) => r.data), // P1.7 alias
  getUserCompanyAccess: (id) => client.get(`/users/${id}/company-access`).then((r) => r.data),
  replaceUserCompanyAccess: (id, assignments) => client.put(`/users/${id}/company-access`, { assignments }).then((r) => r.data),

  listDepartments: () => client.get("/departments").then((r) => r.data),
  createDepartment: (d) => client.post("/departments", d).then((r) => r.data),
  updateDepartment: (id, d) => client.put(`/departments/${id}`, d).then((r) => r.data),
  deleteDepartment: (id) => client.delete(`/departments/${id}`).then((r) => r.data),

  getLogs: (params) => client.get("/logs", { params: params || {} }).then((r) => r.data),
  getJournal: () => client.get("/journal").then((r) => r.data), // deprecated P1.6 compatibility
  downloadReport: (kind, department, year, scenario) => client.get(`/reports/${kind}`, {
    params: { ...(department && department !== "all" ? { department } : {}), ...(year ? { year } : {}), ...(scenario ? { scenario } : {}) }, responseType: "blob",
  }).then((r) => r.data),
  getPnl: (params) => client.get("/reports/pnl", { params }).then((r) => r.data),
  getByClass: (params) => client.get("/reports/by-class", { params }).then((r) => r.data),
  getScenarioCompare: (params) => client.get("/reports/scenario-compare", { params }).then((r) => r.data),
  getCustomColumns: () => client.get("/reports/custom-columns").then((r) => r.data),
  getCustomReport: (params) => client.get("/reports/custom", { params }).then((r) => r.data),
  getPreferences: () => client.get("/me/preferences").then((r) => r.data),
  updatePreferences: (body) => client.put("/me/preferences", body).then((r) => r.data),
  getCompanies: (includeInactive = false) => client.get("/companies", { params: includeInactive ? { include_inactive: true } : {} }).then((r) => r.data),
  previewCompaniesImport: (file) => { const fd = new FormData(); fd.append("file", file); return client.post("/companies/import/preview", fd).then((r) => r.data); },
  commitCompaniesImport: (file) => { const fd = new FormData(); fd.append("file", file); return client.post("/companies/import/commit", fd).then((r) => r.data); },
  getCompany: (id) => client.get(`/companies/${id}`).then((r) => r.data),
  createCompany: (body) => client.post("/companies", body).then((r) => r.data),
  adminCandidate: (email) => client.get("/access/admin-candidate", { params: { email } }).then((r) => r.data),
  requestEmailChange: (new_email) => client.post("/me/email-change/request", { new_email }).then((r) => r.data),
  confirmEmailChange: (token) => client.post("/me/email-change/confirm", { token }).then((r) => r.data),
  changePassword: (current_password, new_password) => client.post("/me/password-change", { current_password, new_password }).then((r) => r.data),
  getCompanyHome: (cid) => client.get(`/companies/${cid}/home`).then((r) => r.data),
  uploadCompanyLogo: (cid, body) => client.post(`/companies/${cid}/logo`, body).then((r) => r.data),
  deleteCompanyLogo: (cid) => client.delete(`/companies/${cid}/logo`).then((r) => r.data),
  getCompanyLogoBlob: (cid) => client.get(`/companies/${cid}/logo`, { responseType: "blob" }).then((r) => r.data),
  getTaxJurisdictionConfig: (params) => client.get(`/tax/jurisdiction-config`, { params }).then((r) => r.data),
  createCompanyMember: (cid, body) => client.post(`/companies/${cid}/members`, body).then((r) => r.data),
  updateCompany: (id, body) => client.patch(`/companies/${id}`, body).then((r) => r.data),
  listMandates: () => client.get("/mandates").then((r) => r.data),
  getMandate: (id) => client.get(`/mandates/${id}`).then((r) => r.data),
  createMandate: (body) => client.post("/mandates", body).then((r) => r.data),
  updateMandate: (id, body) => client.patch(`/mandates/${id}`, body).then((r) => r.data),
  getNotifications: () => client.get("/notifications").then((r) => r.data),
  uploadAvatar: (file) => {
    const fd = new FormData();
    fd.append("file", file);
    return client.post("/me/avatar", fd, { headers: { "Content-Type": "multipart/form-data" } }).then((r) => r.data);
  },
  deleteAvatar: () => client.delete("/me/avatar").then((r) => r.data),
  listReportTemplates: () => client.get("/report-templates").then((r) => r.data),
  createReportTemplate: (body) => client.post("/report-templates", body).then((r) => r.data),
  deleteReportTemplate: (id) => client.delete(`/report-templates/${id}`).then((r) => r.data),
  downloadReportParams: (kind, params) => client.get(`/reports/${kind}`, { params, responseType: "blob" }).then((r) => r.data),

  acctDashboard: () => client.get("/acct/dashboard").then((r) => r.data),
  acctGetTemplate: () => client.get("/acct/template").then((r) => r.data),
  acctUploadTemplate: (file) => { const fd = new FormData(); fd.append("file", file); return client.post("/acct/template", fd).then((r) => r.data); },
  acctUploadBV: (file, params) => { const fd = new FormData(); fd.append("file", file); return client.post("/acct/bv", fd, { params }).then((r) => r.data); },
  acctUploadLedger: (file, params) => { const fd = new FormData(); fd.append("file", file); return client.post("/acct/ledger", fd, { params }).then((r) => r.data); },
  acctUploadLedgerAll: (file) => { const fd = new FormData(); fd.append("file", file); return client.post("/acct/ledger/import-all", fd).then((r) => r.data); },
  acctLedgerStatus: (params) => client.get("/acct/ledger/status", { params }).then((r) => r.data),
  acctLedgerTransactions: (params) => client.get("/acct/ledger/transactions", { params }).then((r) => r.data),
  acctLedgerEntry: (params) => client.get("/acct/ledger/entry", { params }).then((r) => r.data),
  acctLineComments: (params) => client.get("/acct/line-comments", { params }).then((r) => r.data),
  acctLineCommentCounts: (params) => client.get("/acct/line-comments/counts", { params }).then((r) => r.data),
  acctAddLineComment: (body) => client.post("/acct/line-comments", body).then((r) => r.data),
  acctEditLineComment: (cid, body) => client.put(`/acct/line-comments/${cid}`, body).then((r) => r.data),
  acctDeleteLineComment: (cid) => client.delete(`/acct/line-comments/${cid}`).then((r) => r.data),
  acctDeleteLedger: (params) => client.delete("/acct/ledger", { params }).then((r) => r.data),
  acctLedgerTemplate: () => client.get("/acct/ledger/template", { responseType: "blob" }).then((r) => r.data),
  acctPeriods: () => client.get("/acct/periods").then((r) => r.data),
  acctLock: (params) => client.post("/acct/period/lock", {}, { params }).then((r) => r.data),
  acctDeletePeriod: (params) => client.delete("/acct/period", { params }).then((r) => r.data),
  acctReport: (params) => client.get("/acct/report", { params }).then((r) => r.data),
  acctReportExcel: (params) => client.get("/acct/report/excel", { params, responseType: "blob" }).then((r) => r.data),
  acctReportPdf: (params) => client.get("/acct/report/pdf", { params, responseType: "blob" }).then((r) => r.data),
  acctPnlMonthly: (params) => client.get("/acct/report/pnl-monthly", { params }).then((r) => r.data),
  acctBudgetManagers: () => client.get("/acct/budget-managers").then((r) => r.data),
  acctCreateBudgetManager: (body) => client.post("/acct/budget-managers", body).then((r) => r.data),
  acctUpdateBudgetManager: (id, body) => client.put(`/acct/budget-managers/${id}`, body).then((r) => r.data),
  acctDeleteBudgetManager: (id) => client.delete(`/acct/budget-managers/${id}`).then((r) => r.data),
  acctReportByManager: (params) => client.get("/acct/report/by-manager", { params }).then((r) => r.data),
  acctReportByManagerExcel: (params) => client.get("/acct/report/by-manager/excel", { params, responseType: "blob" }).then((r) => r.data),
  acctReportByManagerPdf: (params) => client.get("/acct/report/by-manager/pdf", { params, responseType: "blob" }).then((r) => r.data),
  acctSaveManagerNote: (body) => client.put("/acct/report/by-manager/note", body).then((r) => r.data),
  acctEmailStatus: () => client.get("/acct/email/status").then((r) => r.data),
  acctEmailLog: (params) => client.get("/acct/email/log", { params }).then((r) => r.data),
  acctExternalCatalog: () => client.get("/acct/external/catalog").then((r) => r.data),
  acctExternalContacts: () => client.get("/acct/external-contacts").then((r) => r.data),
  acctCreateExternalContact: (body) => client.post("/acct/external-contacts", body).then((r) => r.data),
  acctUpdateExternalContact: (id, body) => client.put(`/acct/external-contacts/${id}`, body).then((r) => r.data),
  acctDeleteExternalContact: (id) => client.delete(`/acct/external-contacts/${id}`).then((r) => r.data),
  acctMarginationStatus: (params) => client.get("/acct/margination/status", { params }).then((r) => r.data),
  acctMarginationPreview: (params) => client.get("/acct/margination/preview", { params }).then((r) => r.data),
  acctMarginationUpload: (file, params) => { const fd = new FormData(); fd.append("file", file); return client.post("/acct/margination/upload", fd, { params }).then((r) => r.data); },
  acctExternalReport: (params) => client.get("/acct/external/report", { params, responseType: "blob" }).then((r) => r.data),
  acctExternalEmail: (params) => client.post("/acct/external/email", {}, { params }).then((r) => r.data),
  acctExternalEmailLog: (params) => client.get("/acct/external/email/log", { params }).then((r) => r.data),
  acctEmailManager: (params) => client.post("/acct/report/by-manager/email", {}, { params }).then((r) => r.data),
  acctEmailAllManagers: (params) => client.post("/acct/report/by-manager/email-all", {}, { params }).then((r) => r.data),
  acctAccounts: () => client.get("/acct/accounts").then((r) => r.data),
  acctAccountMap: (assignments, params) => client.post("/acct/account-map", { assignments }, { params }).then((r) => r.data),
  acctSummary: (params) => client.get("/acct/summary", { params }).then((r) => r.data),
  acctCashflow: (params) => client.get("/acct/cashflow", { params }).then((r) => r.data),
  acctCashflowExcel: (params) => client.get("/acct/cashflow/excel", { params, responseType: "blob" }).then((r) => r.data),
  acctCashflowPdf: (params) => client.get("/acct/cashflow/pdf", { params, responseType: "blob" }).then((r) => r.data),
  acctTrend: () => client.get("/acct/trend").then((r) => r.data),
  acctKpis: (params) => client.get("/acct/kpis", { params }).then((r) => r.data),
  acctProjections: () => client.get("/acct/projections").then((r) => r.data),
  acctSettings: () => client.get("/acct/settings").then((r) => r.data),
  acctSaveSettings: (body) => client.put("/acct/settings", body).then((r) => r.data),
  acctKpiAdjust: (params, body) => client.put("/acct/kpi-adjust", body, { params }).then((r) => r.data),
  acctAiStatus: () => client.get("/acct/ai/status").then((r) => r.data),
  acctAiGetConfig: () => client.get("/acct/ai/config").then((r) => r.data),
  acctAiSaveConfig: (body) => client.put("/acct/ai/config", body).then((r) => r.data),
  acctAiClearKeys: () => client.delete("/acct/ai/config/key").then((r) => r.data),
  acctAiVariance: (params) => client.post("/acct/ai/variance", {}, { params }).then((r) => r.data),
  acctAiVarianceScenarios: (params) => client.get("/acct/ai/variance/scenarios", { params }).then((r) => r.data),
  acctAiAnomalies: (params) => client.post("/acct/ai/anomalies", {}, { params }).then((r) => r.data),
  acctAiChat: (body) => client.post("/acct/ai/chat", body).then((r) => r.data),
  acctAiSuggestMapping: (body) => client.post("/acct/ai/suggest-mapping", body).then((r) => r.data),
  // --- 9434-3977 QC inc. (entité indépendante) ---
  qcYears: () => client.get("/qc9434/years").then((r) => r.data),
  qcCreateYear: (params) => client.post("/qc9434/years", {}, { params }).then((r) => r.data),
  qcSetActiveYear: (params) => client.put("/qc9434/years/active", {}, { params }).then((r) => r.data),
  qcLockYear: (params) => client.post("/qc9434/years/lock", {}, { params }).then((r) => r.data),
  qcEntries: (params) => client.get("/qc9434/entries", { params }).then((r) => r.data),
  qcCreateEntry: (body, params) => client.post("/qc9434/entries", body, { params }).then((r) => r.data),
  qcUpdateEntry: (id, body) => client.put(`/qc9434/entries/${id}`, body).then((r) => r.data),
  qcDeleteEntry: (id) => client.delete(`/qc9434/entries/${id}`).then((r) => r.data),
  qcTrialBalance: (params) => client.get("/qc9434/trial-balance", { params }).then((r) => r.data),
  qcTrialBalanceExcel: (params) => client.get("/qc9434/trial-balance/excel", { params, responseType: "blob" }).then((r) => r.data),
  qcExternalCatalog: () => client.get("/qc9434/external/catalog").then((r) => r.data),
  qcExternalContacts: () => client.get("/qc9434/external-contacts").then((r) => r.data),
  qcCreateExternalContact: (body) => client.post("/qc9434/external-contacts", body).then((r) => r.data),
  qcUpdateExternalContact: (id, body) => client.put(`/qc9434/external-contacts/${id}`, body).then((r) => r.data),
  qcDeleteExternalContact: (id) => client.delete(`/qc9434/external-contacts/${id}`).then((r) => r.data),
  qcExternalReport: (params) => client.get("/qc9434/external/report", { params, responseType: "blob" }).then((r) => r.data),
  qcExternalEmail: (params) => client.post("/qc9434/external/email", {}, { params }).then((r) => r.data),
  qcExternalEmailLog: (params) => client.get("/qc9434/external/email/log", { params }).then((r) => r.data),
  qcAccounts: () => client.get("/qc9434/accounts").then((r) => r.data),
  qcCreateAccount: (body) => client.post("/qc9434/accounts", body).then((r) => r.data),
  qcUpdateAccount: (gl, body) => client.put(`/qc9434/accounts/${gl}`, body).then((r) => r.data),
  qcDeleteAccount: (gl) => client.delete(`/qc9434/accounts/${gl}`).then((r) => r.data),
  qcBilan: (params) => client.get("/qc9434/bilan", { params }).then((r) => r.data),
  qcPnl: (params) => client.get("/qc9434/pnl", { params }).then((r) => r.data),
  qcBilanExcel: (params) => client.get("/qc9434/bilan/excel", { params, responseType: "blob" }).then((r) => r.data),
  qcPnlExcel: (params) => client.get("/qc9434/pnl/excel", { params, responseType: "blob" }).then((r) => r.data),
  qcJournalPdf: (params) => client.get("/qc9434/journal/pdf", { params, responseType: "blob" }).then((r) => r.data),
  qcTemplates: () => client.get("/qc9434/templates").then((r) => r.data),
  qcCreateTemplate: (body) => client.post("/qc9434/templates", body).then((r) => r.data),
  qcDeleteTemplate: (id) => client.delete(`/qc9434/templates/${id}`).then((r) => r.data),
  qcBilanPdf: (params) => client.get("/qc9434/bilan/pdf", { params, responseType: "blob" }).then((r) => r.data),
  qcPnlPdf: (params) => client.get("/qc9434/pnl/pdf", { params, responseType: "blob" }).then((r) => r.data),
  qcInvoices: (params) => client.get("/qc9434/invoices", { params }).then((r) => r.data),
  qcCreateInvoice: (body, params) => client.post("/qc9434/invoices", body, { params }).then((r) => r.data),
  qcUpdateInvoice: (id, body) => client.put(`/qc9434/invoices/${id}`, body).then((r) => r.data),
  qcReverseInvoice: (id, params) => client.post(`/qc9434/invoices/${id}/reverse`, {}, { params }).then((r) => r.data),
  qcCreateCreditNote: (body, params) => client.post("/qc9434/credit-notes", body, { params }).then((r) => r.data),
  qcClients: () => client.get("/qc9434/clients").then((r) => r.data),
  qcCreateClient: (body) => client.post("/qc9434/clients", body).then((r) => r.data),
  qcUpdateClient: (id, body) => client.put(`/qc9434/clients/${id}`, body).then((r) => r.data),
  qcDeleteClient: (id) => client.delete(`/qc9434/clients/${id}`).then((r) => r.data),
  qcClientStatement: (id, params) => client.get(`/qc9434/clients/${id}/statement`, { params }).then((r) => r.data),
  qcClientStatementPdf: (id, params) => client.get(`/qc9434/clients/${id}/statement/pdf`, { params, responseType: "blob" }).then((r) => r.data),
  qcPurgeTestData: () => client.post("/qc9434/purge-test-data", {}).then((r) => r.data),
  qcReceiveInvoice: (id, params) => client.post(`/qc9434/invoices/${id}/receive`, {}, { params }).then((r) => r.data),
  qcInvoicePdf: (id) => client.get(`/qc9434/invoices/${id}/pdf`, { responseType: "blob" }).then((r) => r.data),
  qcBills: (params) => client.get("/qc9434/bills", { params }).then((r) => r.data),
  qcCreateBill: (formData) => client.post("/qc9434/bills", formData, { headers: { "Content-Type": "multipart/form-data" } }).then((r) => r.data),
  qcBillExtract: (file) => { const fd = new FormData(); fd.append("file", file); return client.post("/qc9434/bills/extract", fd, { headers: { "Content-Type": "multipart/form-data" }, timeout: 60000 }).then((r) => r.data); },
  qcPayBill: (id, params) => client.post(`/qc9434/bills/${id}/pay`, {}, { params }).then((r) => r.data),
  qcImportModel: () => client.post("/qc9434/import-model", {}).then((r) => r.data),
  qcGetOpening: (year) => client.get(`/qc9434/opening/${year}`).then((r) => r.data),
  qcPutOpening: (year, body) => client.put(`/qc9434/opening/${year}`, body).then((r) => r.data),
  qcEmailInvoice: (id) => client.post(`/qc9434/invoices/${id}/email`, {}).then((r) => r.data),
  qcInvoicePayments: (id) => client.get(`/qc9434/invoices/${id}/payments`).then((r) => r.data),
  qcInvoiceSendReminders: (params) => client.post("/qc9434/invoices/send-reminders", {}, { params }).then((r) => r.data),
  qcBillPayments: (id) => client.get(`/qc9434/bills/${id}/payments`).then((r) => r.data),
  qcAccountDetail: (params) => client.get("/qc9434/account-detail", { params }).then((r) => r.data),
  qcEtatsFinanciers: (params) => client.get("/qc9434/etats-financiers", { params }).then((r) => r.data),
  qcEfPdf: (params) => client.get("/qc9434/etats-financiers/pdf", { params, responseType: "blob" }).then((r) => r.data),
  qcEfExcel: (params) => client.get("/qc9434/etats-financiers/excel", { params, responseType: "blob" }).then((r) => r.data),
  qcEfSettings: () => client.get("/qc9434/ef-settings").then((r) => r.data),
  qcEfSettingsUpdate: (body) => client.put("/qc9434/ef-settings", body).then((r) => r.data),

  // P1.13B/C/D — access lifecycle & governance
  activationPreview: (token) => client.get(`/auth/activation/${token}`).then((r) => r.data),
  activate: (token, password, name) => client.post("/auth/activate", { token, password, name }).then((r) => r.data),
  accessModules: () => client.get("/access/modules").then((r) => r.data),
  accessPermissions: (module) => client.get("/access/permissions", { params: module ? { module } : {} }).then((r) => r.data),
  listInvitations: (status) => client.get("/workspace/invitations", { params: status ? { status } : {} }).then((r) => r.data),
  getInvitation: (id) => client.get(`/workspace/invitations/${id}`).then((r) => r.data),
  createInvitation: (body) => client.post("/workspace/invitations", body).then((r) => r.data),
  resendInvitation: (id) => client.post(`/workspace/invitations/${id}/resend`).then((r) => r.data),
  revokeInvitation: (id) => client.post(`/workspace/invitations/${id}/revoke`).then((r) => r.data),
  listAccessUsers: () => client.get("/workspace/users").then((r) => r.data),
  getAccessUser: (uid) => client.get(`/workspace/users/${uid}`).then((r) => r.data),
  setIdentityStatus: (uid, status) => client.post(`/workspace/users/${uid}/identity-status`, { status }).then((r) => r.data),
  wsEntitlements: () => client.get("/workspace/module-entitlements").then((r) => r.data),
  moduleMatrix: (cid, uid) => client.get(`/companies/${cid}/users/${uid}/module-matrix`).then((r) => r.data),
  setModuleAccess: (cid, uid, code, level) => client.put(`/companies/${cid}/users/${uid}/module-access/${code}`, { access_level: level }).then((r) => r.data),
  setUserPermission: (cid, uid, code, granted) => client.put(`/companies/${cid}/users/${uid}/permissions/${code}`, { granted }).then((r) => r.data),
  explainAccess: (cid, uid, params) => client.get(`/companies/${cid}/users/${uid}/effective-access/explain`, { params }).then((r) => r.data),
  companyAdminHistory: (cid) => client.get(`/companies/${cid}/admin-history`).then((r) => r.data),
  replaceCompanyAdmin: (cid, body) => client.post(`/companies/${cid}/client-admin/replace`, body).then((r) => r.data),

  // P1.13D.2 — Meelora platform console (platform staff only)
  // P1.13E — dynamic navigation manifest (backend is the authority)
  getCompanyContext: () => client.get("/me/company-context").then((r) => r.data),
  getCompanyNavigation: (cid) => client.get(`/companies/${cid}/navigation`).then((r) => r.data),

  platformSummary: () => client.get("/platform/summary").then((r) => r.data),
  platformClients: () => client.get("/platform/clients").then((r) => r.data),
  platformLogs: (params) => client.get("/platform/logs", { params: params || {} }).then((r) => r.data),
  platformClient: (wsId) => client.get(`/platform/clients/${wsId}`).then((r) => r.data),
  platformClientAdmins: (wsId) => client.get(`/platform/clients/${wsId}/administrators`).then((r) => r.data),
  platformClientUsers: (wsId) => client.get(`/platform/clients/${wsId}/users`).then((r) => r.data),
  platformClientModules: (wsId) => client.get(`/platform/clients/${wsId}/modules`).then((r) => r.data),
  platformClientLogs: (wsId, params) => client.get(`/platform/clients/${wsId}/logs`, { params: params || {} }).then((r) => r.data),
  platformClientSupport: (wsId) => client.get(`/platform/clients/${wsId}/support`).then((r) => r.data),
  platformCompanies: () => client.get("/platform/companies").then((r) => r.data),
  platformCompanyMembers: (cid) => client.get(`/platform/companies/${cid}/members`).then((r) => r.data),
  // ACCOUNTING A2 — Core GL
  glPeriods: (cid) => client.get(`/companies/${cid}/gl/periods`).then((r) => r.data),
  glCreatePeriod: (cid, body) => client.post(`/companies/${cid}/gl/periods`, body).then((r) => r.data),
  glTransitionPeriod: (cid, pid, status) => client.post(`/companies/${cid}/gl/periods/${pid}/transition`, { status }).then((r) => r.data),
  glEntries: (cid, params) => client.get(`/companies/${cid}/gl/entries`, { params }).then((r) => r.data),
  glEntry: (cid, eid) => client.get(`/companies/${cid}/gl/entries/${eid}`).then((r) => r.data),
  glCreateEntry: (cid, body) => client.post(`/companies/${cid}/gl/entries`, body).then((r) => r.data),
  glSubmitEntry: (cid, eid) => client.post(`/companies/${cid}/gl/entries/${eid}/submit`).then((r) => r.data),
  glApproveEntry: (cid, eid) => client.post(`/companies/${cid}/gl/entries/${eid}/approve`).then((r) => r.data),
  glPostEntry: (cid, eid) => client.post(`/companies/${cid}/gl/entries/${eid}/post`).then((r) => r.data),
  glReverseEntry: (cid, eid, body) => client.post(`/companies/${cid}/gl/entries/${eid}/reverse`, body || {}).then((r) => r.data),
  // ACCOUNTING A3 — Accounts Receivable (Ventes & Clients)
  arTaxCodes: (cid) => client.get(`/companies/${cid}/ar/tax-codes`).then((r) => r.data),
  arSeedTaxCodes: (cid) => client.post(`/companies/${cid}/ar/tax-codes/seed`).then((r) => r.data),
  arCreateTaxCode: (cid, body) => client.post(`/companies/${cid}/ar/tax-codes`, body).then((r) => r.data),
  apSuppliers: (cid) => client.get(`/companies/${cid}/ap/suppliers`).then((r) => r.data),
  apSupplier: (cid, id) => client.get(`/companies/${cid}/ap/suppliers/${id}`).then((r) => r.data),
  apCreateSupplier: (cid, body) => client.post(`/companies/${cid}/ap/suppliers`, body).then((r) => r.data),
  apUpdateSupplier: (cid, id, body) => client.patch(`/companies/${cid}/ap/suppliers/${id}`, body).then((r) => r.data),
  apInvoices: (cid, params) => client.get(`/companies/${cid}/ap/invoices`, { params }).then((r) => r.data),
  apInvoice: (cid, id) => client.get(`/companies/${cid}/ap/invoices/${id}`).then((r) => r.data),
  apCreateInvoice: (cid, body) => client.post(`/companies/${cid}/ap/invoices`, body).then((r) => r.data),
  apInvoiceAction: (cid, id, action, body) => client.post(`/companies/${cid}/ap/invoices/${id}/${action}`, body || {}).then((r) => r.data),
  apUploadInvoicePdf: (cid, id, file) => { const fd = new FormData(); fd.append("file", file); return client.post(`/companies/${cid}/ap/invoices/${id}/attachment`, fd, { headers: { "Content-Type": "multipart/form-data" } }).then((r) => r.data); },
  apInvoiceDocuments: (cid, id) => client.get(`/companies/${cid}/ap/invoices/${id}/documents`).then((r) => r.data),
  // A4.3 — payments · credit notes · aging · batches
  apOverview: (cid, params) => client.get(`/companies/${cid}/ap/overview`, { params }).then((r) => r.data),
  apPayments: (cid, params) => client.get(`/companies/${cid}/ap/payments`, { params }).then((r) => r.data),
  apPayment: (cid, id) => client.get(`/companies/${cid}/ap/payments/${id}`).then((r) => r.data),
  apCreatePayment: (cid, body) => client.post(`/companies/${cid}/ap/payments`, body).then((r) => r.data),
  apUpdatePayment: (cid, id, body) => client.patch(`/companies/${cid}/ap/payments/${id}`, body).then((r) => r.data),
  apPaymentAction: (cid, id, action, body) => client.post(`/companies/${cid}/ap/payments/${id}/${action}`, body || {}).then((r) => r.data),
  apCreditNotes: (cid, params) => client.get(`/companies/${cid}/ap/credit-notes`, { params }).then((r) => r.data),
  apCreditNote: (cid, id) => client.get(`/companies/${cid}/ap/credit-notes/${id}`).then((r) => r.data),
  apCreateCreditNote: (cid, body) => client.post(`/companies/${cid}/ap/credit-notes`, body).then((r) => r.data),
  apCreditNoteAction: (cid, id, action, body) => client.post(`/companies/${cid}/ap/credit-notes/${id}/${action}`, body || {}).then((r) => r.data),
  apAging: (cid, params) => client.get(`/companies/${cid}/ap/aging`, { params }).then((r) => r.data),
  apReconciliation: (cid, params) => client.get(`/companies/${cid}/ap/reconciliation`, { params }).then((r) => r.data),
  apRevaluations: (cid, params) => client.get(`/companies/${cid}/ap/fx-revaluations`, { params }).then((r) => r.data),
  apRevaluation: (cid, id) => client.get(`/companies/${cid}/ap/fx-revaluations/${id}`).then((r) => r.data),
  apCalculateRevaluation: (cid, body) => client.post(`/companies/${cid}/ap/fx-revaluations/calculate`, body).then((r) => r.data),
  apPostRevaluation: (cid, id) => client.post(`/companies/${cid}/ap/fx-revaluations/${id}/post`).then((r) => r.data),
  apPostRevaluationReversal: (cid, id) => client.post(`/companies/${cid}/ap/fx-revaluations/${id}/post-reversal`).then((r) => r.data),
  apSupplierSummary: (cid, sid, params) => client.get(`/companies/${cid}/ap/suppliers/${sid}/summary`, { params }).then((r) => r.data),
  apBatchCandidates: (cid, params) => client.get(`/companies/${cid}/ap/batch-candidates`, { params }).then((r) => r.data),
  apBatches: (cid, params) => client.get(`/companies/${cid}/ap/batches`, { params }).then((r) => r.data),
  apBatch: (cid, id) => client.get(`/companies/${cid}/ap/batches/${id}`).then((r) => r.data),
  apCreateBatch: (cid, body) => client.post(`/companies/${cid}/ap/batches`, body).then((r) => r.data),
  apBatchAction: (cid, id, action, body) => client.post(`/companies/${cid}/ap/batches/${id}/${action}`, body || {}).then((r) => r.data),
  apRevalidateBatch: (cid, id) => client.get(`/companies/${cid}/ap/batches/${id}/revalidate`).then((r) => r.data),
  // A4.4 — Analyse automatique des documents (IA assistance)
  apDocAiStatus: (cid) => client.get(`/companies/${cid}/ap/document-ai/status`).then((r) => r.data),
  apDocAiAnalyze: (cid, body) => client.post(`/companies/${cid}/ap/document-ai/analyze`, body || {}).then((r) => r.data),
  apExtraction: (cid, xid) => client.get(`/companies/${cid}/ap/extractions/${xid}`).then((r) => r.data),
  apExtractionCorrections: (cid, xid, body) => client.post(`/companies/${cid}/ap/extractions/${xid}/corrections`, body).then((r) => r.data),
  // A4.5 — Purchase orders + matching
  apSettings: (cid) => client.get(`/companies/${cid}/ap/settings`).then((r) => r.data),
  apSetSettings: (cid, body) => client.put(`/companies/${cid}/ap/settings`, body).then((r) => r.data),
  poList: (cid, params) => client.get(`/companies/${cid}/ap/purchase-orders`, { params }).then((r) => r.data),
  po: (cid, id) => client.get(`/companies/${cid}/ap/purchase-orders/${id}`).then((r) => r.data),
  poCreate: (cid, body) => client.post(`/companies/${cid}/ap/purchase-orders`, body).then((r) => r.data),
  poAction: (cid, id, action, body) => client.post(`/companies/${cid}/ap/purchase-orders/${id}/${action}`, body || {}).then((r) => r.data),
  apMatch: (cid, invId, body) => client.post(`/companies/${cid}/ap/invoices/${invId}/match`, body).then((r) => r.data),
  apMatchOverride: (cid, invId, body) => client.post(`/companies/${cid}/ap/invoices/${invId}/match-override`, body).then((r) => r.data),
  arMapping: (cid) => client.get(`/companies/${cid}/ar/mapping`).then((r) => r.data),
  arSetMapping: (cid, body) => client.put(`/companies/${cid}/ar/mapping`, body).then((r) => r.data),
  arRecordFxRate: (cid, body) => client.post(`/companies/${cid}/ar/fx-rates`, body).then((r) => r.data),
  arOandaRate: (cid, params) => client.get(`/companies/${cid}/ar/fx-oanda`, { params }).then((r) => r.data),
  arCustomers: (cid) => client.get(`/companies/${cid}/ar/customers`).then((r) => r.data),
  arCreateCustomer: (cid, body) => client.post(`/companies/${cid}/ar/customers`, body).then((r) => r.data),
  arUpdateCustomer: (cid, id, body) => client.patch(`/companies/${cid}/ar/customers/${id}`, body).then((r) => r.data),
  arInvoices: (cid, params) => client.get(`/companies/${cid}/ar/invoices`, { params }).then((r) => r.data),
  arInvoice: (cid, id) => client.get(`/companies/${cid}/ar/invoices/${id}`).then((r) => r.data),
  arCreateInvoice: (cid, body) => client.post(`/companies/${cid}/ar/invoices`, body).then((r) => r.data),
  arUpdateInvoice: (cid, id, body) => client.patch(`/companies/${cid}/ar/invoices/${id}`, body).then((r) => r.data),
  arSubmitInvoice: (cid, id) => client.post(`/companies/${cid}/ar/invoices/${id}/submit`).then((r) => r.data),
  arApproveInvoice: (cid, id) => client.post(`/companies/${cid}/ar/invoices/${id}/approve`).then((r) => r.data),
  arPostInvoice: (cid, id) => client.post(`/companies/${cid}/ar/invoices/${id}/post`).then((r) => r.data),
  arVoidInvoice: (cid, id) => client.post(`/companies/${cid}/ar/invoices/${id}/void`).then((r) => r.data),
  arPayments: (cid, params) => client.get(`/companies/${cid}/ar/payments`, { params }).then((r) => r.data),
  arCreatePayment: (cid, body) => client.post(`/companies/${cid}/ar/payments`, body).then((r) => r.data),
  arCreditNotes: (cid, params) => client.get(`/companies/${cid}/ar/credit-notes`, { params }).then((r) => r.data),
  arCreateCreditNote: (cid, body) => client.post(`/companies/${cid}/ar/credit-notes`, body).then((r) => r.data),
  arSubmitCreditNote: (cid, id) => client.post(`/companies/${cid}/ar/credit-notes/${id}/submit`).then((r) => r.data),
  arApproveCreditNote: (cid, id) => client.post(`/companies/${cid}/ar/credit-notes/${id}/approve`).then((r) => r.data),
  arPostCreditNote: (cid, id) => client.post(`/companies/${cid}/ar/credit-notes/${id}/post`).then((r) => r.data),
  arAging: (cid, params) => client.get(`/companies/${cid}/ar/aging`, { params }).then((r) => r.data),
  arOverview: (cid, params) => client.get(`/companies/${cid}/ar/overview`, { params }).then((r) => r.data),
  arInvoiceDocuments: (cid, id) => client.get(`/companies/${cid}/ar/invoices/${id}/documents`).then((r) => r.data),
  arDownloadDocument: (cid, docId) => client.get(`/companies/${cid}/documents/${docId}/download`, { responseType: "blob" }).then((r) => r.data),
  arJournalSource: (cid, jeId) => client.get(`/companies/${cid}/journal-source/${jeId}`).then((r) => r.data),
  arOverdue: (cid, params) => client.get(`/companies/${cid}/ar/overdue`, { params }).then((r) => r.data),
  arReminders: (cid, params) => client.get(`/companies/${cid}/ar/reminders`, { params }).then((r) => r.data),
  arCreateReminder: (cid, body) => client.post(`/companies/${cid}/ar/reminders`, body).then((r) => r.data),
  arDunningPolicy: (cid) => client.get(`/companies/${cid}/ar/reminders/policy`).then((r) => r.data),
  arSetDunningPolicy: (cid, body) => client.put(`/companies/${cid}/ar/reminders/policy`, body).then((r) => r.data),
  arReminderSuggestions: (cid, params) => client.get(`/companies/${cid}/ar/reminders/suggestions`, { params }).then((r) => r.data),
};
